---
plugin: amazon.aws.aws_ec2

aws_access_key: AKIA2UC3CKSK7G2FEJLP
aws_secret_key: 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

regions:
- eu-west-3

keyed_groups:
  - key: tags
    prefix: tag
  - prefix: instance_type
    key: instance_type
  - key: placement.region
    prefix: aws_region