---
- name: Cluster 
  hosts: localhost
  environment:
    AWS_ACCESS_KEY: "{{ aws_access_key }}"
    AWS_SECRET_KEY: "{{ aws_secret_key }}"
  vars_files:
    - roles/eks/vars/vars.yaml
  remote_user: root
  roles:
    - eks
